// This file is auto-generated by @hey-api/openapi-ts

export type ApprovalCreate = {
    /**
     * Email build to submit for approval
     */
    build_id: number;
    /**
     * Project ID
     */
    project_id: number;
};

export type ApprovalDecision = {
    status: string;
    review_note?: string | null;
};

export type ApprovalResponse = {
    id: number;
    build_id: number;
    project_id: number;
    status: string;
    requested_by_id: number;
    reviewed_by_id?: number | null;
    review_note?: string | null;
    created_at: string;
    updated_at: string;
};

export type AuditResponse = {
    id: number;
    approval_id: number;
    action: string;
    actor_id: number;
    details?: string | null;
    created_at: string;
};

export type BodyUploadDocumentApiV1KnowledgeDocumentsPost = {
    file: string;
    domain: string;
    language?: string;
    metadata_json?: string | null;
    title?: string | null;
    description?: string | null;
};

/**
 * Request to build an email template.
 */
export type BuildRequest = {
    /**
     * Project ID
     */
    project_id: number;
    template_name: string;
    /**
     * Maizzle template source
     */
    source_html: string;
    /**
     * Maizzle config overrides
     */
    config_overrides?: {
        [key: string]: unknown;
    } | null;
    /**
     * Use production config
     */
    is_production?: boolean;
};

/**
 * Response from a build execution.
 */
export type BuildResponse = {
    id: number;
    project_id: number;
    template_name: string;
    status: string;
    compiled_html?: string | null;
    error_message?: string | null;
    is_production: boolean;
    created_at: string;
};

/**
 * A single completion choice in the response.
 *
 * Attributes:
 * index: The index of this choice in the list.
 * message: The assistant's response message.
 * finish_reason: Why the completion stopped.
 */
export type ChatCompletionChoice = {
    index?: number;
    message: ChatMessage;
    finish_reason?: string;
};

/**
 * Request body for the chat completions endpoint.
 *
 * Attributes:
 * messages: List of messages in the conversation (at least one required).
 * model: Optional model override (ignored in MVP, uses server config).
 */
export type ChatCompletionRequest = {
    messages: Array<ChatMessage>;
    model?: string | null;
};

/**
 * Response from the chat completions endpoint.
 *
 * Follows the OpenAI Chat Completions API response format.
 *
 * Attributes:
 * id: Unique identifier for this completion.
 * object: Object type (always "chat.completion").
 * created: Unix timestamp when the completion was created.
 * model: The model used for the completion.
 * choices: List of completion choices.
 * usage: Token usage information.
 */
export type ChatCompletionResponse = {
    id?: string;
    object?: 'chat.completion';
    created?: number;
    model: string;
    choices: Array<ChatCompletionChoice>;
    usage?: UsageInfo;
};

/**
 * A single message in a chat conversation.
 *
 * Attributes:
 * role: The role of the message sender.
 * content: The text content of the message.
 */
export type ChatMessage = {
    role: 'user' | 'assistant' | 'system';
    content: string;
};

export type ClientOrgCreate = {
    /**
     * Client organization name
     */
    name: string;
    /**
     * URL-safe slug
     */
    slug: string;
};

export type ClientOrgResponse = {
    /**
     * Client organization name
     */
    name: string;
    /**
     * URL-safe slug
     */
    slug: string;
    id: number;
    is_active: boolean;
    created_at: string;
    updated_at: string;
};

export type ComponentCreate = {
    name: string;
    slug: string;
    description?: string | null;
    category?: string;
    /**
     * Initial HTML source
     */
    html_source: string;
    css_source?: string | null;
};

export type ComponentResponse = {
    name: string;
    slug: string;
    description?: string | null;
    category?: string;
    id: number;
    created_by_id: number;
    created_at: string;
    updated_at: string;
    latest_version?: number | null;
};

export type ComponentUpdate = {
    name?: string | null;
    description?: string | null;
    category?: string | null;
};

/**
 * Admin creates a new user.
 */
export type CreateUserRequest = {
    email: string;
    name: string;
    password: string;
    role?: string;
};

/**
 * Schema for a single document chunk.
 */
export type DocumentChunkResponse = {
    chunk_index: number;
    content: string;
};

/**
 * Schema wrapping document metadata with its text chunks.
 */
export type DocumentContentResponse = {
    document_id: number;
    filename: string;
    title: string | null;
    total_chunks: number;
    chunks: Array<DocumentChunkResponse>;
};

/**
 * Schema for document responses.
 */
export type DocumentResponseReadable = {
    id: number;
    filename: string;
    title: string | null;
    description: string | null;
    domain: string;
    source_type: string;
    language: string;
    file_size_bytes: number | null;
    status: string;
    error_message: string | null;
    chunk_count: number;
    metadata_json: string | null;
    ocr_applied: boolean;
    tags?: Array<TagResponse>;
    created_at: string;
    updated_at: string;
    /**
     * Whether the original file is stored on disk.
     */
    readonly has_file: boolean;
};

/**
 * Schema for document responses.
 */
export type DocumentResponseWritable = {
    id: number;
    filename: string;
    title: string | null;
    description: string | null;
    domain: string;
    source_type: string;
    language: string;
    file_size_bytes: number | null;
    status: string;
    error_message: string | null;
    chunk_count: number;
    metadata_json: string | null;
    ocr_applied: boolean;
    tags?: Array<TagResponse>;
    created_at: string;
    updated_at: string;
};

/**
 * Schema for adding tags to a document.
 */
export type DocumentTagRequest = {
    /**
     * Tag IDs to assign
     */
    tag_ids: Array<number>;
};

/**
 * Schema for updating document metadata (PATCH semantics).
 */
export type DocumentUpdate = {
    title?: string | null;
    description?: string | null;
    domain?: string | null;
    language?: string | null;
};

/**
 * Schema for listing unique knowledge domains.
 */
export type DomainListResponse = {
    domains: Array<string>;
    total: number;
};

/**
 * Request to export an email build to an ESP.
 */
export type ExportRequest = {
    /**
     * Email build ID to export
     */
    build_id: number;
    connector_type?: string;
    /**
     * Name for the ESP content block
     */
    content_block_name: string;
};

/**
 * Response from an export operation.
 */
export type ExportResponse = {
    id: number;
    build_id: number;
    connector_type: string;
    status: string;
    external_id?: string | null;
    error_message?: string | null;
    created_at: string;
};

export type FeedbackCreate = {
    content: string;
    feedback_type?: string;
};

export type FeedbackResponse = {
    id: number;
    approval_id: number;
    author_id: number;
    content: string;
    feedback_type: string;
    created_at: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Schema for creating an item.
 */
export type ItemCreate = {
    /**
     * Item name
     */
    name: string;
    /**
     * Item description
     */
    description?: string | null;
    /**
     * Status: active/archived
     */
    status?: string;
};

/**
 * Schema for item responses.
 */
export type ItemResponse = {
    /**
     * Item name
     */
    name: string;
    /**
     * Item description
     */
    description?: string | null;
    /**
     * Status: active/archived
     */
    status?: string;
    id: number;
    is_active: boolean;
    created_at: string;
    updated_at: string;
};

/**
 * Schema for updating an item. All fields optional.
 */
export type ItemUpdate = {
    name?: string | null;
    description?: string | null;
    status?: string | null;
    is_active?: boolean | null;
};

/**
 * Login credentials.
 */
export type LoginRequest = {
    email: string;
    password: string;
};

/**
 * Successful login response with JWT tokens.
 */
export type LoginResponse = {
    id: number;
    email: string;
    name: string;
    role: string;
    access_token: string;
    refresh_token: string;
};

export type PaginatedResponseClientOrgResponse = {
    items: Array<ClientOrgResponse>;
    total: number;
    page: number;
    page_size: number;
};

export type PaginatedResponseComponentResponse = {
    items: Array<ComponentResponse>;
    total: number;
    page: number;
    page_size: number;
};

export type PaginatedResponseDocumentResponseReadable = {
    items: Array<DocumentResponseReadable>;
    total: number;
    page: number;
    page_size: number;
};

export type PaginatedResponseDocumentResponseWritable = {
    items: Array<DocumentResponseWritable>;
    total: number;
    page: number;
    page_size: number;
};

export type PaginatedResponseItemResponse = {
    items: Array<ItemResponse>;
    total: number;
    page: number;
    page_size: number;
};

export type PaginatedResponseProjectResponse = {
    items: Array<ProjectResponse>;
    total: number;
    page: number;
    page_size: number;
};

export type PaginatedResponseUserDetailResponse = {
    items: Array<UserDetailResponse>;
    total: number;
    page: number;
    page_size: number;
};

/**
 * Admin-initiated password reset.
 */
export type PasswordResetRequest = {
    user_id: number;
    new_password: string;
};

export type PersonaCreate = {
    name: string;
    slug: string;
    description?: string | null;
    email_client?: string;
    device_type?: string;
    dark_mode?: boolean;
    viewport_width?: number;
    os_name?: string;
};

export type PersonaResponse = {
    name: string;
    slug: string;
    description?: string | null;
    email_client?: string;
    device_type?: string;
    dark_mode?: boolean;
    viewport_width?: number;
    os_name?: string;
    id: number;
    is_preset: boolean;
    created_at: string;
    updated_at: string;
};

/**
 * Request for a live preview build.
 */
export type PreviewRequest = {
    source_html: string;
    config_overrides?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Response from a preview build.
 */
export type PreviewResponse = {
    compiled_html: string;
    build_time_ms: number;
};

export type ProjectCreate = {
    /**
     * Project name
     */
    name: string;
    /**
     * Project description
     */
    description?: string | null;
    /**
     * Client organization ID
     */
    client_org_id: number;
};

export type ProjectResponse = {
    /**
     * Project name
     */
    name: string;
    /**
     * Project description
     */
    description?: string | null;
    /**
     * Client organization ID
     */
    client_org_id: number;
    id: number;
    status: string;
    created_by_id: number;
    is_active: boolean;
    created_at: string;
    updated_at: string;
};

export type ProjectUpdate = {
    name?: string | null;
    description?: string | null;
    status?: string | null;
    is_active?: boolean | null;
};

/**
 * Result of a single QA check.
 */
export type QaCheckResult = {
    check_name: string;
    passed: boolean;
    score: number;
    details?: string | null;
    severity?: string;
};

/**
 * Full QA result with individual checks.
 */
export type QaResultResponse = {
    id: number;
    build_id: number;
    overall_score: number;
    passed: boolean;
    checks_passed: number;
    checks_total: number;
    checks?: Array<QaCheckResult>;
    created_at: string;
};

/**
 * Request to run QA checks on compiled HTML.
 */
export type QaRunRequest = {
    /**
     * Email build ID to validate
     */
    build_id: number;
    /**
     * Compiled HTML to validate
     */
    html: string;
};

/**
 * Token refresh request.
 */
export type RefreshRequest = {
    refresh_token: string;
};

/**
 * Token refresh response.
 */
export type RefreshResponse = {
    access_token: string;
};

/**
 * Schema for knowledge base search.
 */
export type SearchRequest = {
    /**
     * Search query text
     */
    query: string;
    /**
     * Filter by domain
     */
    domain?: string | null;
    /**
     * Filter by language
     */
    language?: string | null;
    /**
     * Max results to return
     */
    limit?: number;
};

/**
 * Search response with results and metadata.
 */
export type SearchResponse = {
    results: Array<SearchResult>;
    query: string;
    total_candidates: number;
    reranked: boolean;
};

/**
 * Single search result with relevance score.
 */
export type SearchResult = {
    chunk_content: string;
    document_id: number;
    document_filename: string;
    domain: string;
    language: string;
    chunk_index: number;
    score: number;
    metadata_json: string | null;
};

/**
 * Schema for creating a new tag.
 */
export type TagCreate = {
    /**
     * Tag name
     */
    name: string;
};

/**
 * Schema for listing all tags.
 */
export type TagListResponse = {
    tags: Array<TagResponse>;
    total: number;
};

/**
 * Schema for tag responses.
 */
export type TagResponse = {
    id: number;
    name: string;
    created_at: string;
};

/**
 * Admin updates user fields.
 */
export type UpdateUserRequest = {
    name?: string | null;
    email?: string | null;
    role?: string | null;
    is_active?: boolean | null;
};

/**
 * Token usage information for the completion.
 *
 * Attributes:
 * prompt_tokens: Tokens used in the prompt.
 * completion_tokens: Tokens generated in the response.
 * total_tokens: Total tokens used.
 */
export type UsageInfo = {
    prompt_tokens?: number;
    completion_tokens?: number;
    total_tokens?: number;
};

/**
 * User detail with timestamps.
 */
export type UserDetailResponse = {
    id: number;
    email: string;
    name: string;
    role: string;
    is_active: boolean;
    created_at: string;
    updated_at: string;
};

/**
 * Public user information.
 */
export type UserResponse = {
    id: number;
    email: string;
    name: string;
    role: string;
    is_active: boolean;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type VersionCreate = {
    html_source: string;
    css_source?: string | null;
    changelog?: string | null;
};

export type VersionResponse = {
    id: number;
    component_id: number;
    version_number: number;
    html_source: string;
    css_source: string | null;
    changelog: string | null;
    created_by_id: number;
    created_at: string;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];

export type DatabaseHealthCheckHealthDbGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/db';
};

export type DatabaseHealthCheckHealthDbGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type DatabaseHealthCheckHealthDbGetResponse = DatabaseHealthCheckHealthDbGetResponses[keyof DatabaseHealthCheckHealthDbGetResponses];

export type HealthRedisHealthRedisGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/redis';
};

export type HealthRedisHealthRedisGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthRedisHealthRedisGetResponse = HealthRedisHealthRedisGetResponses[keyof HealthRedisHealthRedisGetResponses];

export type ReadinessCheckHealthReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type ReadinessCheckHealthReadyGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type ReadinessCheckHealthReadyGetResponse = ReadinessCheckHealthReadyGetResponses[keyof ReadinessCheckHealthReadyGetResponses];

export type LoginApiV1AuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type RefreshTokenApiV1AuthRefreshPostData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshTokenApiV1AuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshTokenApiV1AuthRefreshPostError = RefreshTokenApiV1AuthRefreshPostErrors[keyof RefreshTokenApiV1AuthRefreshPostErrors];

export type RefreshTokenApiV1AuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: RefreshResponse;
};

export type RefreshTokenApiV1AuthRefreshPostResponse = RefreshTokenApiV1AuthRefreshPostResponses[keyof RefreshTokenApiV1AuthRefreshPostResponses];

export type LogoutApiV1AuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutApiV1AuthLogoutPostResponse = LogoutApiV1AuthLogoutPostResponses[keyof LogoutApiV1AuthLogoutPostResponses];

export type ResetPasswordApiV1AuthResetPasswordPostData = {
    body: PasswordResetRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/reset-password';
};

export type ResetPasswordApiV1AuthResetPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetPasswordApiV1AuthResetPasswordPostError = ResetPasswordApiV1AuthResetPasswordPostErrors[keyof ResetPasswordApiV1AuthResetPasswordPostErrors];

export type ResetPasswordApiV1AuthResetPasswordPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ResetPasswordApiV1AuthResetPasswordPostResponse = ResetPasswordApiV1AuthResetPasswordPostResponses[keyof ResetPasswordApiV1AuthResetPasswordPostResponses];

export type SeedDemoUsersApiV1AuthSeedPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/seed';
};

export type SeedDemoUsersApiV1AuthSeedPostResponses = {
    /**
     * Successful Response
     */
    200: Array<UserResponse>;
};

export type SeedDemoUsersApiV1AuthSeedPostResponse = SeedDemoUsersApiV1AuthSeedPostResponses[keyof SeedDemoUsersApiV1AuthSeedPostResponses];

export type ListUsersApiV1AuthUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
        search?: string | null;
        role?: string | null;
        is_active?: boolean | null;
    };
    url: '/api/v1/auth/users';
};

export type ListUsersApiV1AuthUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListUsersApiV1AuthUsersGetError = ListUsersApiV1AuthUsersGetErrors[keyof ListUsersApiV1AuthUsersGetErrors];

export type ListUsersApiV1AuthUsersGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseUserDetailResponse;
};

export type ListUsersApiV1AuthUsersGetResponse = ListUsersApiV1AuthUsersGetResponses[keyof ListUsersApiV1AuthUsersGetResponses];

export type CreateUserApiV1AuthUsersPostData = {
    body: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/users';
};

export type CreateUserApiV1AuthUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiV1AuthUsersPostError = CreateUserApiV1AuthUsersPostErrors[keyof CreateUserApiV1AuthUsersPostErrors];

export type CreateUserApiV1AuthUsersPostResponses = {
    /**
     * Successful Response
     */
    201: UserDetailResponse;
};

export type CreateUserApiV1AuthUsersPostResponse = CreateUserApiV1AuthUsersPostResponses[keyof CreateUserApiV1AuthUsersPostResponses];

export type DeleteUserDataApiV1AuthUsersUserIdDeleteData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: never;
    url: '/api/v1/auth/users/{user_id}';
};

export type DeleteUserDataApiV1AuthUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserDataApiV1AuthUsersUserIdDeleteError = DeleteUserDataApiV1AuthUsersUserIdDeleteErrors[keyof DeleteUserDataApiV1AuthUsersUserIdDeleteErrors];

export type DeleteUserDataApiV1AuthUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserDataApiV1AuthUsersUserIdDeleteResponse = DeleteUserDataApiV1AuthUsersUserIdDeleteResponses[keyof DeleteUserDataApiV1AuthUsersUserIdDeleteResponses];

export type GetUserApiV1AuthUsersUserIdGetData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: never;
    url: '/api/v1/auth/users/{user_id}';
};

export type GetUserApiV1AuthUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserApiV1AuthUsersUserIdGetError = GetUserApiV1AuthUsersUserIdGetErrors[keyof GetUserApiV1AuthUsersUserIdGetErrors];

export type GetUserApiV1AuthUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserDetailResponse;
};

export type GetUserApiV1AuthUsersUserIdGetResponse = GetUserApiV1AuthUsersUserIdGetResponses[keyof GetUserApiV1AuthUsersUserIdGetResponses];

export type UpdateUserApiV1AuthUsersUserIdPatchData = {
    body: UpdateUserRequest;
    path: {
        user_id: number;
    };
    query?: never;
    url: '/api/v1/auth/users/{user_id}';
};

export type UpdateUserApiV1AuthUsersUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiV1AuthUsersUserIdPatchError = UpdateUserApiV1AuthUsersUserIdPatchErrors[keyof UpdateUserApiV1AuthUsersUserIdPatchErrors];

export type UpdateUserApiV1AuthUsersUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserDetailResponse;
};

export type UpdateUserApiV1AuthUsersUserIdPatchResponse = UpdateUserApiV1AuthUsersUserIdPatchResponses[keyof UpdateUserApiV1AuthUsersUserIdPatchResponses];

export type ListItemsApiV1ItemsGetData = {
    body?: never;
    path?: never;
    query?: {
        search?: string | null;
        active_only?: boolean;
        status?: string | null;
        page?: number;
        page_size?: number;
    };
    url: '/api/v1/items/';
};

export type ListItemsApiV1ItemsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListItemsApiV1ItemsGetError = ListItemsApiV1ItemsGetErrors[keyof ListItemsApiV1ItemsGetErrors];

export type ListItemsApiV1ItemsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseItemResponse;
};

export type ListItemsApiV1ItemsGetResponse = ListItemsApiV1ItemsGetResponses[keyof ListItemsApiV1ItemsGetResponses];

export type CreateItemApiV1ItemsPostData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type CreateItemApiV1ItemsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateItemApiV1ItemsPostError = CreateItemApiV1ItemsPostErrors[keyof CreateItemApiV1ItemsPostErrors];

export type CreateItemApiV1ItemsPostResponses = {
    /**
     * Successful Response
     */
    201: ItemResponse;
};

export type CreateItemApiV1ItemsPostResponse = CreateItemApiV1ItemsPostResponses[keyof CreateItemApiV1ItemsPostResponses];

export type DeleteItemApiV1ItemsItemIdDeleteData = {
    body?: never;
    path: {
        item_id: number;
    };
    query?: never;
    url: '/api/v1/items/{item_id}';
};

export type DeleteItemApiV1ItemsItemIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemApiV1ItemsItemIdDeleteError = DeleteItemApiV1ItemsItemIdDeleteErrors[keyof DeleteItemApiV1ItemsItemIdDeleteErrors];

export type DeleteItemApiV1ItemsItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteItemApiV1ItemsItemIdDeleteResponse = DeleteItemApiV1ItemsItemIdDeleteResponses[keyof DeleteItemApiV1ItemsItemIdDeleteResponses];

export type GetItemApiV1ItemsItemIdGetData = {
    body?: never;
    path: {
        item_id: number;
    };
    query?: never;
    url: '/api/v1/items/{item_id}';
};

export type GetItemApiV1ItemsItemIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemApiV1ItemsItemIdGetError = GetItemApiV1ItemsItemIdGetErrors[keyof GetItemApiV1ItemsItemIdGetErrors];

export type GetItemApiV1ItemsItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: ItemResponse;
};

export type GetItemApiV1ItemsItemIdGetResponse = GetItemApiV1ItemsItemIdGetResponses[keyof GetItemApiV1ItemsItemIdGetResponses];

export type UpdateItemApiV1ItemsItemIdPatchData = {
    body: ItemUpdate;
    path: {
        item_id: number;
    };
    query?: never;
    url: '/api/v1/items/{item_id}';
};

export type UpdateItemApiV1ItemsItemIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateItemApiV1ItemsItemIdPatchError = UpdateItemApiV1ItemsItemIdPatchErrors[keyof UpdateItemApiV1ItemsItemIdPatchErrors];

export type UpdateItemApiV1ItemsItemIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ItemResponse;
};

export type UpdateItemApiV1ItemsItemIdPatchResponse = UpdateItemApiV1ItemsItemIdPatchResponses[keyof UpdateItemApiV1ItemsItemIdPatchResponses];

export type ChatCompletionsV1ChatCompletionsPostData = {
    body: ChatCompletionRequest;
    path?: never;
    query?: never;
    url: '/v1/chat/completions';
};

export type ChatCompletionsV1ChatCompletionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatCompletionsV1ChatCompletionsPostError = ChatCompletionsV1ChatCompletionsPostErrors[keyof ChatCompletionsV1ChatCompletionsPostErrors];

export type ChatCompletionsV1ChatCompletionsPostResponses = {
    /**
     * Successful Response
     */
    200: ChatCompletionResponse;
};

export type ChatCompletionsV1ChatCompletionsPostResponse = ChatCompletionsV1ChatCompletionsPostResponses[keyof ChatCompletionsV1ChatCompletionsPostResponses];

export type ListModelsV1ModelsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/models';
};

export type ListModelsV1ModelsGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ListModelsV1ModelsGetResponse = ListModelsV1ModelsGetResponses[keyof ListModelsV1ModelsGetResponses];

export type ListDocumentsApiV1KnowledgeDocumentsGetData = {
    body?: never;
    path?: never;
    query?: {
        domain?: string | null;
        status?: string | null;
        tag?: string | null;
        page?: number;
        page_size?: number;
    };
    url: '/api/v1/knowledge/documents';
};

export type ListDocumentsApiV1KnowledgeDocumentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDocumentsApiV1KnowledgeDocumentsGetError = ListDocumentsApiV1KnowledgeDocumentsGetErrors[keyof ListDocumentsApiV1KnowledgeDocumentsGetErrors];

export type ListDocumentsApiV1KnowledgeDocumentsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseDocumentResponseReadable;
};

export type ListDocumentsApiV1KnowledgeDocumentsGetResponse = ListDocumentsApiV1KnowledgeDocumentsGetResponses[keyof ListDocumentsApiV1KnowledgeDocumentsGetResponses];

export type UploadDocumentApiV1KnowledgeDocumentsPostData = {
    body: BodyUploadDocumentApiV1KnowledgeDocumentsPost;
    path?: never;
    query?: never;
    url: '/api/v1/knowledge/documents';
};

export type UploadDocumentApiV1KnowledgeDocumentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadDocumentApiV1KnowledgeDocumentsPostError = UploadDocumentApiV1KnowledgeDocumentsPostErrors[keyof UploadDocumentApiV1KnowledgeDocumentsPostErrors];

export type UploadDocumentApiV1KnowledgeDocumentsPostResponses = {
    /**
     * Successful Response
     */
    201: DocumentResponseReadable;
};

export type UploadDocumentApiV1KnowledgeDocumentsPostResponse = UploadDocumentApiV1KnowledgeDocumentsPostResponses[keyof UploadDocumentApiV1KnowledgeDocumentsPostResponses];

export type DeleteDocumentApiV1KnowledgeDocumentsDocumentIdDeleteData = {
    body?: never;
    path: {
        document_id: number;
    };
    query?: never;
    url: '/api/v1/knowledge/documents/{document_id}';
};

export type DeleteDocumentApiV1KnowledgeDocumentsDocumentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDocumentApiV1KnowledgeDocumentsDocumentIdDeleteError = DeleteDocumentApiV1KnowledgeDocumentsDocumentIdDeleteErrors[keyof DeleteDocumentApiV1KnowledgeDocumentsDocumentIdDeleteErrors];

export type DeleteDocumentApiV1KnowledgeDocumentsDocumentIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteDocumentApiV1KnowledgeDocumentsDocumentIdDeleteResponse = DeleteDocumentApiV1KnowledgeDocumentsDocumentIdDeleteResponses[keyof DeleteDocumentApiV1KnowledgeDocumentsDocumentIdDeleteResponses];

export type GetDocumentApiV1KnowledgeDocumentsDocumentIdGetData = {
    body?: never;
    path: {
        document_id: number;
    };
    query?: never;
    url: '/api/v1/knowledge/documents/{document_id}';
};

export type GetDocumentApiV1KnowledgeDocumentsDocumentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDocumentApiV1KnowledgeDocumentsDocumentIdGetError = GetDocumentApiV1KnowledgeDocumentsDocumentIdGetErrors[keyof GetDocumentApiV1KnowledgeDocumentsDocumentIdGetErrors];

export type GetDocumentApiV1KnowledgeDocumentsDocumentIdGetResponses = {
    /**
     * Successful Response
     */
    200: DocumentResponseReadable;
};

export type GetDocumentApiV1KnowledgeDocumentsDocumentIdGetResponse = GetDocumentApiV1KnowledgeDocumentsDocumentIdGetResponses[keyof GetDocumentApiV1KnowledgeDocumentsDocumentIdGetResponses];

export type UpdateDocumentApiV1KnowledgeDocumentsDocumentIdPatchData = {
    body: DocumentUpdate;
    path: {
        document_id: number;
    };
    query?: never;
    url: '/api/v1/knowledge/documents/{document_id}';
};

export type UpdateDocumentApiV1KnowledgeDocumentsDocumentIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDocumentApiV1KnowledgeDocumentsDocumentIdPatchError = UpdateDocumentApiV1KnowledgeDocumentsDocumentIdPatchErrors[keyof UpdateDocumentApiV1KnowledgeDocumentsDocumentIdPatchErrors];

export type UpdateDocumentApiV1KnowledgeDocumentsDocumentIdPatchResponses = {
    /**
     * Successful Response
     */
    200: DocumentResponseReadable;
};

export type UpdateDocumentApiV1KnowledgeDocumentsDocumentIdPatchResponse = UpdateDocumentApiV1KnowledgeDocumentsDocumentIdPatchResponses[keyof UpdateDocumentApiV1KnowledgeDocumentsDocumentIdPatchResponses];

export type DownloadDocumentApiV1KnowledgeDocumentsDocumentIdDownloadGetData = {
    body?: never;
    path: {
        document_id: number;
    };
    query?: never;
    url: '/api/v1/knowledge/documents/{document_id}/download';
};

export type DownloadDocumentApiV1KnowledgeDocumentsDocumentIdDownloadGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadDocumentApiV1KnowledgeDocumentsDocumentIdDownloadGetError = DownloadDocumentApiV1KnowledgeDocumentsDocumentIdDownloadGetErrors[keyof DownloadDocumentApiV1KnowledgeDocumentsDocumentIdDownloadGetErrors];

export type DownloadDocumentApiV1KnowledgeDocumentsDocumentIdDownloadGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetDocumentContentApiV1KnowledgeDocumentsDocumentIdContentGetData = {
    body?: never;
    path: {
        document_id: number;
    };
    query?: never;
    url: '/api/v1/knowledge/documents/{document_id}/content';
};

export type GetDocumentContentApiV1KnowledgeDocumentsDocumentIdContentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDocumentContentApiV1KnowledgeDocumentsDocumentIdContentGetError = GetDocumentContentApiV1KnowledgeDocumentsDocumentIdContentGetErrors[keyof GetDocumentContentApiV1KnowledgeDocumentsDocumentIdContentGetErrors];

export type GetDocumentContentApiV1KnowledgeDocumentsDocumentIdContentGetResponses = {
    /**
     * Successful Response
     */
    200: DocumentContentResponse;
};

export type GetDocumentContentApiV1KnowledgeDocumentsDocumentIdContentGetResponse = GetDocumentContentApiV1KnowledgeDocumentsDocumentIdContentGetResponses[keyof GetDocumentContentApiV1KnowledgeDocumentsDocumentIdContentGetResponses];

export type ListDomainsApiV1KnowledgeDomainsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/knowledge/domains';
};

export type ListDomainsApiV1KnowledgeDomainsGetResponses = {
    /**
     * Successful Response
     */
    200: DomainListResponse;
};

export type ListDomainsApiV1KnowledgeDomainsGetResponse = ListDomainsApiV1KnowledgeDomainsGetResponses[keyof ListDomainsApiV1KnowledgeDomainsGetResponses];

export type ListTagsApiV1KnowledgeTagsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/knowledge/tags';
};

export type ListTagsApiV1KnowledgeTagsGetResponses = {
    /**
     * Successful Response
     */
    200: TagListResponse;
};

export type ListTagsApiV1KnowledgeTagsGetResponse = ListTagsApiV1KnowledgeTagsGetResponses[keyof ListTagsApiV1KnowledgeTagsGetResponses];

export type CreateTagApiV1KnowledgeTagsPostData = {
    body: TagCreate;
    path?: never;
    query?: never;
    url: '/api/v1/knowledge/tags';
};

export type CreateTagApiV1KnowledgeTagsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTagApiV1KnowledgeTagsPostError = CreateTagApiV1KnowledgeTagsPostErrors[keyof CreateTagApiV1KnowledgeTagsPostErrors];

export type CreateTagApiV1KnowledgeTagsPostResponses = {
    /**
     * Successful Response
     */
    201: TagResponse;
};

export type CreateTagApiV1KnowledgeTagsPostResponse = CreateTagApiV1KnowledgeTagsPostResponses[keyof CreateTagApiV1KnowledgeTagsPostResponses];

export type DeleteTagApiV1KnowledgeTagsTagIdDeleteData = {
    body?: never;
    path: {
        tag_id: number;
    };
    query?: never;
    url: '/api/v1/knowledge/tags/{tag_id}';
};

export type DeleteTagApiV1KnowledgeTagsTagIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTagApiV1KnowledgeTagsTagIdDeleteError = DeleteTagApiV1KnowledgeTagsTagIdDeleteErrors[keyof DeleteTagApiV1KnowledgeTagsTagIdDeleteErrors];

export type DeleteTagApiV1KnowledgeTagsTagIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTagApiV1KnowledgeTagsTagIdDeleteResponse = DeleteTagApiV1KnowledgeTagsTagIdDeleteResponses[keyof DeleteTagApiV1KnowledgeTagsTagIdDeleteResponses];

export type AddTagsToDocumentApiV1KnowledgeDocumentsDocumentIdTagsPostData = {
    body: DocumentTagRequest;
    path: {
        document_id: number;
    };
    query?: never;
    url: '/api/v1/knowledge/documents/{document_id}/tags';
};

export type AddTagsToDocumentApiV1KnowledgeDocumentsDocumentIdTagsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddTagsToDocumentApiV1KnowledgeDocumentsDocumentIdTagsPostError = AddTagsToDocumentApiV1KnowledgeDocumentsDocumentIdTagsPostErrors[keyof AddTagsToDocumentApiV1KnowledgeDocumentsDocumentIdTagsPostErrors];

export type AddTagsToDocumentApiV1KnowledgeDocumentsDocumentIdTagsPostResponses = {
    /**
     * Successful Response
     */
    200: DocumentResponseReadable;
};

export type AddTagsToDocumentApiV1KnowledgeDocumentsDocumentIdTagsPostResponse = AddTagsToDocumentApiV1KnowledgeDocumentsDocumentIdTagsPostResponses[keyof AddTagsToDocumentApiV1KnowledgeDocumentsDocumentIdTagsPostResponses];

export type RemoveTagFromDocumentApiV1KnowledgeDocumentsDocumentIdTagsTagIdDeleteData = {
    body?: never;
    path: {
        document_id: number;
        tag_id: number;
    };
    query?: never;
    url: '/api/v1/knowledge/documents/{document_id}/tags/{tag_id}';
};

export type RemoveTagFromDocumentApiV1KnowledgeDocumentsDocumentIdTagsTagIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveTagFromDocumentApiV1KnowledgeDocumentsDocumentIdTagsTagIdDeleteError = RemoveTagFromDocumentApiV1KnowledgeDocumentsDocumentIdTagsTagIdDeleteErrors[keyof RemoveTagFromDocumentApiV1KnowledgeDocumentsDocumentIdTagsTagIdDeleteErrors];

export type RemoveTagFromDocumentApiV1KnowledgeDocumentsDocumentIdTagsTagIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DocumentResponseReadable;
};

export type RemoveTagFromDocumentApiV1KnowledgeDocumentsDocumentIdTagsTagIdDeleteResponse = RemoveTagFromDocumentApiV1KnowledgeDocumentsDocumentIdTagsTagIdDeleteResponses[keyof RemoveTagFromDocumentApiV1KnowledgeDocumentsDocumentIdTagsTagIdDeleteResponses];

export type SearchKnowledgeApiV1KnowledgeSearchPostData = {
    body: SearchRequest;
    path?: never;
    query?: never;
    url: '/api/v1/knowledge/search';
};

export type SearchKnowledgeApiV1KnowledgeSearchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchKnowledgeApiV1KnowledgeSearchPostError = SearchKnowledgeApiV1KnowledgeSearchPostErrors[keyof SearchKnowledgeApiV1KnowledgeSearchPostErrors];

export type SearchKnowledgeApiV1KnowledgeSearchPostResponses = {
    /**
     * Successful Response
     */
    200: SearchResponse;
};

export type SearchKnowledgeApiV1KnowledgeSearchPostResponse = SearchKnowledgeApiV1KnowledgeSearchPostResponses[keyof SearchKnowledgeApiV1KnowledgeSearchPostResponses];

export type ListOrgsApiV1OrgsGetData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
    };
    url: '/api/v1/orgs';
};

export type ListOrgsApiV1OrgsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListOrgsApiV1OrgsGetError = ListOrgsApiV1OrgsGetErrors[keyof ListOrgsApiV1OrgsGetErrors];

export type ListOrgsApiV1OrgsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseClientOrgResponse;
};

export type ListOrgsApiV1OrgsGetResponse = ListOrgsApiV1OrgsGetResponses[keyof ListOrgsApiV1OrgsGetResponses];

export type CreateOrgApiV1OrgsPostData = {
    body: ClientOrgCreate;
    path?: never;
    query?: never;
    url: '/api/v1/orgs';
};

export type CreateOrgApiV1OrgsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOrgApiV1OrgsPostError = CreateOrgApiV1OrgsPostErrors[keyof CreateOrgApiV1OrgsPostErrors];

export type CreateOrgApiV1OrgsPostResponses = {
    /**
     * Successful Response
     */
    201: ClientOrgResponse;
};

export type CreateOrgApiV1OrgsPostResponse = CreateOrgApiV1OrgsPostResponses[keyof CreateOrgApiV1OrgsPostResponses];

export type ListProjectsApiV1ProjectsGetData = {
    body?: never;
    path?: never;
    query?: {
        client_org_id?: number | null;
        search?: string | null;
        page?: number;
        page_size?: number;
    };
    url: '/api/v1/projects';
};

export type ListProjectsApiV1ProjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProjectsApiV1ProjectsGetError = ListProjectsApiV1ProjectsGetErrors[keyof ListProjectsApiV1ProjectsGetErrors];

export type ListProjectsApiV1ProjectsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseProjectResponse;
};

export type ListProjectsApiV1ProjectsGetResponse = ListProjectsApiV1ProjectsGetResponses[keyof ListProjectsApiV1ProjectsGetResponses];

export type CreateProjectApiV1ProjectsPostData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/api/v1/projects';
};

export type CreateProjectApiV1ProjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectApiV1ProjectsPostError = CreateProjectApiV1ProjectsPostErrors[keyof CreateProjectApiV1ProjectsPostErrors];

export type CreateProjectApiV1ProjectsPostResponses = {
    /**
     * Successful Response
     */
    201: ProjectResponse;
};

export type CreateProjectApiV1ProjectsPostResponse = CreateProjectApiV1ProjectsPostResponses[keyof CreateProjectApiV1ProjectsPostResponses];

export type DeleteProjectApiV1ProjectsProjectIdDeleteData = {
    body?: never;
    path: {
        project_id: number;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type DeleteProjectApiV1ProjectsProjectIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectApiV1ProjectsProjectIdDeleteError = DeleteProjectApiV1ProjectsProjectIdDeleteErrors[keyof DeleteProjectApiV1ProjectsProjectIdDeleteErrors];

export type DeleteProjectApiV1ProjectsProjectIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProjectApiV1ProjectsProjectIdDeleteResponse = DeleteProjectApiV1ProjectsProjectIdDeleteResponses[keyof DeleteProjectApiV1ProjectsProjectIdDeleteResponses];

export type GetProjectApiV1ProjectsProjectIdGetData = {
    body?: never;
    path: {
        project_id: number;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type GetProjectApiV1ProjectsProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectApiV1ProjectsProjectIdGetError = GetProjectApiV1ProjectsProjectIdGetErrors[keyof GetProjectApiV1ProjectsProjectIdGetErrors];

export type GetProjectApiV1ProjectsProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type GetProjectApiV1ProjectsProjectIdGetResponse = GetProjectApiV1ProjectsProjectIdGetResponses[keyof GetProjectApiV1ProjectsProjectIdGetResponses];

export type UpdateProjectApiV1ProjectsProjectIdPatchData = {
    body: ProjectUpdate;
    path: {
        project_id: number;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type UpdateProjectApiV1ProjectsProjectIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProjectApiV1ProjectsProjectIdPatchError = UpdateProjectApiV1ProjectsProjectIdPatchErrors[keyof UpdateProjectApiV1ProjectsProjectIdPatchErrors];

export type UpdateProjectApiV1ProjectsProjectIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type UpdateProjectApiV1ProjectsProjectIdPatchResponse = UpdateProjectApiV1ProjectsProjectIdPatchResponses[keyof UpdateProjectApiV1ProjectsProjectIdPatchResponses];

export type BuildEmailApiV1EmailBuildPostData = {
    body: BuildRequest;
    path?: never;
    query?: never;
    url: '/api/v1/email/build';
};

export type BuildEmailApiV1EmailBuildPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BuildEmailApiV1EmailBuildPostError = BuildEmailApiV1EmailBuildPostErrors[keyof BuildEmailApiV1EmailBuildPostErrors];

export type BuildEmailApiV1EmailBuildPostResponses = {
    /**
     * Successful Response
     */
    201: BuildResponse;
};

export type BuildEmailApiV1EmailBuildPostResponse = BuildEmailApiV1EmailBuildPostResponses[keyof BuildEmailApiV1EmailBuildPostResponses];

export type PreviewEmailApiV1EmailPreviewPostData = {
    body: PreviewRequest;
    path?: never;
    query?: never;
    url: '/api/v1/email/preview';
};

export type PreviewEmailApiV1EmailPreviewPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PreviewEmailApiV1EmailPreviewPostError = PreviewEmailApiV1EmailPreviewPostErrors[keyof PreviewEmailApiV1EmailPreviewPostErrors];

export type PreviewEmailApiV1EmailPreviewPostResponses = {
    /**
     * Successful Response
     */
    200: PreviewResponse;
};

export type PreviewEmailApiV1EmailPreviewPostResponse = PreviewEmailApiV1EmailPreviewPostResponses[keyof PreviewEmailApiV1EmailPreviewPostResponses];

export type ListComponentsApiV1ComponentsGetData = {
    body?: never;
    path?: never;
    query?: {
        category?: string | null;
        search?: string | null;
        page?: number;
        page_size?: number;
    };
    url: '/api/v1/components/';
};

export type ListComponentsApiV1ComponentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListComponentsApiV1ComponentsGetError = ListComponentsApiV1ComponentsGetErrors[keyof ListComponentsApiV1ComponentsGetErrors];

export type ListComponentsApiV1ComponentsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseComponentResponse;
};

export type ListComponentsApiV1ComponentsGetResponse = ListComponentsApiV1ComponentsGetResponses[keyof ListComponentsApiV1ComponentsGetResponses];

export type CreateComponentApiV1ComponentsPostData = {
    body: ComponentCreate;
    path?: never;
    query?: never;
    url: '/api/v1/components/';
};

export type CreateComponentApiV1ComponentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateComponentApiV1ComponentsPostError = CreateComponentApiV1ComponentsPostErrors[keyof CreateComponentApiV1ComponentsPostErrors];

export type CreateComponentApiV1ComponentsPostResponses = {
    /**
     * Successful Response
     */
    201: ComponentResponse;
};

export type CreateComponentApiV1ComponentsPostResponse = CreateComponentApiV1ComponentsPostResponses[keyof CreateComponentApiV1ComponentsPostResponses];

export type DeleteComponentApiV1ComponentsComponentIdDeleteData = {
    body?: never;
    path: {
        component_id: number;
    };
    query?: never;
    url: '/api/v1/components/{component_id}';
};

export type DeleteComponentApiV1ComponentsComponentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteComponentApiV1ComponentsComponentIdDeleteError = DeleteComponentApiV1ComponentsComponentIdDeleteErrors[keyof DeleteComponentApiV1ComponentsComponentIdDeleteErrors];

export type DeleteComponentApiV1ComponentsComponentIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteComponentApiV1ComponentsComponentIdDeleteResponse = DeleteComponentApiV1ComponentsComponentIdDeleteResponses[keyof DeleteComponentApiV1ComponentsComponentIdDeleteResponses];

export type GetComponentApiV1ComponentsComponentIdGetData = {
    body?: never;
    path: {
        component_id: number;
    };
    query?: never;
    url: '/api/v1/components/{component_id}';
};

export type GetComponentApiV1ComponentsComponentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetComponentApiV1ComponentsComponentIdGetError = GetComponentApiV1ComponentsComponentIdGetErrors[keyof GetComponentApiV1ComponentsComponentIdGetErrors];

export type GetComponentApiV1ComponentsComponentIdGetResponses = {
    /**
     * Successful Response
     */
    200: ComponentResponse;
};

export type GetComponentApiV1ComponentsComponentIdGetResponse = GetComponentApiV1ComponentsComponentIdGetResponses[keyof GetComponentApiV1ComponentsComponentIdGetResponses];

export type UpdateComponentApiV1ComponentsComponentIdPatchData = {
    body: ComponentUpdate;
    path: {
        component_id: number;
    };
    query?: never;
    url: '/api/v1/components/{component_id}';
};

export type UpdateComponentApiV1ComponentsComponentIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateComponentApiV1ComponentsComponentIdPatchError = UpdateComponentApiV1ComponentsComponentIdPatchErrors[keyof UpdateComponentApiV1ComponentsComponentIdPatchErrors];

export type UpdateComponentApiV1ComponentsComponentIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ComponentResponse;
};

export type UpdateComponentApiV1ComponentsComponentIdPatchResponse = UpdateComponentApiV1ComponentsComponentIdPatchResponses[keyof UpdateComponentApiV1ComponentsComponentIdPatchResponses];

export type ListVersionsApiV1ComponentsComponentIdVersionsGetData = {
    body?: never;
    path: {
        component_id: number;
    };
    query?: never;
    url: '/api/v1/components/{component_id}/versions';
};

export type ListVersionsApiV1ComponentsComponentIdVersionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListVersionsApiV1ComponentsComponentIdVersionsGetError = ListVersionsApiV1ComponentsComponentIdVersionsGetErrors[keyof ListVersionsApiV1ComponentsComponentIdVersionsGetErrors];

export type ListVersionsApiV1ComponentsComponentIdVersionsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<VersionResponse>;
};

export type ListVersionsApiV1ComponentsComponentIdVersionsGetResponse = ListVersionsApiV1ComponentsComponentIdVersionsGetResponses[keyof ListVersionsApiV1ComponentsComponentIdVersionsGetResponses];

export type CreateVersionApiV1ComponentsComponentIdVersionsPostData = {
    body: VersionCreate;
    path: {
        component_id: number;
    };
    query?: never;
    url: '/api/v1/components/{component_id}/versions';
};

export type CreateVersionApiV1ComponentsComponentIdVersionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateVersionApiV1ComponentsComponentIdVersionsPostError = CreateVersionApiV1ComponentsComponentIdVersionsPostErrors[keyof CreateVersionApiV1ComponentsComponentIdVersionsPostErrors];

export type CreateVersionApiV1ComponentsComponentIdVersionsPostResponses = {
    /**
     * Successful Response
     */
    201: VersionResponse;
};

export type CreateVersionApiV1ComponentsComponentIdVersionsPostResponse = CreateVersionApiV1ComponentsComponentIdVersionsPostResponses[keyof CreateVersionApiV1ComponentsComponentIdVersionsPostResponses];

export type RunQaChecksApiV1QaRunPostData = {
    body: QaRunRequest;
    path?: never;
    query?: never;
    url: '/api/v1/qa/run';
};

export type RunQaChecksApiV1QaRunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunQaChecksApiV1QaRunPostError = RunQaChecksApiV1QaRunPostErrors[keyof RunQaChecksApiV1QaRunPostErrors];

export type RunQaChecksApiV1QaRunPostResponses = {
    /**
     * Successful Response
     */
    201: QaResultResponse;
};

export type RunQaChecksApiV1QaRunPostResponse = RunQaChecksApiV1QaRunPostResponses[keyof RunQaChecksApiV1QaRunPostResponses];

export type ExportEmailApiV1ConnectorsExportPostData = {
    body: ExportRequest;
    path?: never;
    query?: never;
    url: '/api/v1/connectors/export';
};

export type ExportEmailApiV1ConnectorsExportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportEmailApiV1ConnectorsExportPostError = ExportEmailApiV1ConnectorsExportPostErrors[keyof ExportEmailApiV1ConnectorsExportPostErrors];

export type ExportEmailApiV1ConnectorsExportPostResponses = {
    /**
     * Successful Response
     */
    201: ExportResponse;
};

export type ExportEmailApiV1ConnectorsExportPostResponse = ExportEmailApiV1ConnectorsExportPostResponses[keyof ExportEmailApiV1ConnectorsExportPostResponses];

export type CreateApprovalApiV1ApprovalsPostData = {
    body: ApprovalCreate;
    path?: never;
    query?: never;
    url: '/api/v1/approvals/';
};

export type CreateApprovalApiV1ApprovalsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateApprovalApiV1ApprovalsPostError = CreateApprovalApiV1ApprovalsPostErrors[keyof CreateApprovalApiV1ApprovalsPostErrors];

export type CreateApprovalApiV1ApprovalsPostResponses = {
    /**
     * Successful Response
     */
    201: ApprovalResponse;
};

export type CreateApprovalApiV1ApprovalsPostResponse = CreateApprovalApiV1ApprovalsPostResponses[keyof CreateApprovalApiV1ApprovalsPostResponses];

export type GetApprovalApiV1ApprovalsApprovalIdGetData = {
    body?: never;
    path: {
        approval_id: number;
    };
    query?: never;
    url: '/api/v1/approvals/{approval_id}';
};

export type GetApprovalApiV1ApprovalsApprovalIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApprovalApiV1ApprovalsApprovalIdGetError = GetApprovalApiV1ApprovalsApprovalIdGetErrors[keyof GetApprovalApiV1ApprovalsApprovalIdGetErrors];

export type GetApprovalApiV1ApprovalsApprovalIdGetResponses = {
    /**
     * Successful Response
     */
    200: ApprovalResponse;
};

export type GetApprovalApiV1ApprovalsApprovalIdGetResponse = GetApprovalApiV1ApprovalsApprovalIdGetResponses[keyof GetApprovalApiV1ApprovalsApprovalIdGetResponses];

export type DecideApprovalApiV1ApprovalsApprovalIdDecidePostData = {
    body: ApprovalDecision;
    path: {
        approval_id: number;
    };
    query?: never;
    url: '/api/v1/approvals/{approval_id}/decide';
};

export type DecideApprovalApiV1ApprovalsApprovalIdDecidePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DecideApprovalApiV1ApprovalsApprovalIdDecidePostError = DecideApprovalApiV1ApprovalsApprovalIdDecidePostErrors[keyof DecideApprovalApiV1ApprovalsApprovalIdDecidePostErrors];

export type DecideApprovalApiV1ApprovalsApprovalIdDecidePostResponses = {
    /**
     * Successful Response
     */
    200: ApprovalResponse;
};

export type DecideApprovalApiV1ApprovalsApprovalIdDecidePostResponse = DecideApprovalApiV1ApprovalsApprovalIdDecidePostResponses[keyof DecideApprovalApiV1ApprovalsApprovalIdDecidePostResponses];

export type ListFeedbackApiV1ApprovalsApprovalIdFeedbackGetData = {
    body?: never;
    path: {
        approval_id: number;
    };
    query?: never;
    url: '/api/v1/approvals/{approval_id}/feedback';
};

export type ListFeedbackApiV1ApprovalsApprovalIdFeedbackGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListFeedbackApiV1ApprovalsApprovalIdFeedbackGetError = ListFeedbackApiV1ApprovalsApprovalIdFeedbackGetErrors[keyof ListFeedbackApiV1ApprovalsApprovalIdFeedbackGetErrors];

export type ListFeedbackApiV1ApprovalsApprovalIdFeedbackGetResponses = {
    /**
     * Successful Response
     */
    200: Array<FeedbackResponse>;
};

export type ListFeedbackApiV1ApprovalsApprovalIdFeedbackGetResponse = ListFeedbackApiV1ApprovalsApprovalIdFeedbackGetResponses[keyof ListFeedbackApiV1ApprovalsApprovalIdFeedbackGetResponses];

export type AddFeedbackApiV1ApprovalsApprovalIdFeedbackPostData = {
    body: FeedbackCreate;
    path: {
        approval_id: number;
    };
    query?: never;
    url: '/api/v1/approvals/{approval_id}/feedback';
};

export type AddFeedbackApiV1ApprovalsApprovalIdFeedbackPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddFeedbackApiV1ApprovalsApprovalIdFeedbackPostError = AddFeedbackApiV1ApprovalsApprovalIdFeedbackPostErrors[keyof AddFeedbackApiV1ApprovalsApprovalIdFeedbackPostErrors];

export type AddFeedbackApiV1ApprovalsApprovalIdFeedbackPostResponses = {
    /**
     * Successful Response
     */
    201: FeedbackResponse;
};

export type AddFeedbackApiV1ApprovalsApprovalIdFeedbackPostResponse = AddFeedbackApiV1ApprovalsApprovalIdFeedbackPostResponses[keyof AddFeedbackApiV1ApprovalsApprovalIdFeedbackPostResponses];

export type GetAuditTrailApiV1ApprovalsApprovalIdAuditGetData = {
    body?: never;
    path: {
        approval_id: number;
    };
    query?: never;
    url: '/api/v1/approvals/{approval_id}/audit';
};

export type GetAuditTrailApiV1ApprovalsApprovalIdAuditGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAuditTrailApiV1ApprovalsApprovalIdAuditGetError = GetAuditTrailApiV1ApprovalsApprovalIdAuditGetErrors[keyof GetAuditTrailApiV1ApprovalsApprovalIdAuditGetErrors];

export type GetAuditTrailApiV1ApprovalsApprovalIdAuditGetResponses = {
    /**
     * Successful Response
     */
    200: Array<AuditResponse>;
};

export type GetAuditTrailApiV1ApprovalsApprovalIdAuditGetResponse = GetAuditTrailApiV1ApprovalsApprovalIdAuditGetResponses[keyof GetAuditTrailApiV1ApprovalsApprovalIdAuditGetResponses];

export type ListPersonasApiV1PersonasGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/personas/';
};

export type ListPersonasApiV1PersonasGetResponses = {
    /**
     * Successful Response
     */
    200: Array<PersonaResponse>;
};

export type ListPersonasApiV1PersonasGetResponse = ListPersonasApiV1PersonasGetResponses[keyof ListPersonasApiV1PersonasGetResponses];

export type CreatePersonaApiV1PersonasPostData = {
    body: PersonaCreate;
    path?: never;
    query?: never;
    url: '/api/v1/personas/';
};

export type CreatePersonaApiV1PersonasPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePersonaApiV1PersonasPostError = CreatePersonaApiV1PersonasPostErrors[keyof CreatePersonaApiV1PersonasPostErrors];

export type CreatePersonaApiV1PersonasPostResponses = {
    /**
     * Successful Response
     */
    201: PersonaResponse;
};

export type CreatePersonaApiV1PersonasPostResponse = CreatePersonaApiV1PersonasPostResponses[keyof CreatePersonaApiV1PersonasPostResponses];

export type GetPersonaApiV1PersonasPersonaIdGetData = {
    body?: never;
    path: {
        persona_id: number;
    };
    query?: never;
    url: '/api/v1/personas/{persona_id}';
};

export type GetPersonaApiV1PersonasPersonaIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPersonaApiV1PersonasPersonaIdGetError = GetPersonaApiV1PersonasPersonaIdGetErrors[keyof GetPersonaApiV1PersonasPersonaIdGetErrors];

export type GetPersonaApiV1PersonasPersonaIdGetResponses = {
    /**
     * Successful Response
     */
    200: PersonaResponse;
};

export type GetPersonaApiV1PersonasPersonaIdGetResponse = GetPersonaApiV1PersonasPersonaIdGetResponses[keyof GetPersonaApiV1PersonasPersonaIdGetResponses];

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type ReadRootGetResponse = ReadRootGetResponses[keyof ReadRootGetResponses];

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};