// Approval Package — Client-Facing Document
// Reads data from data.json (written by TypstRenderer)

#let data = json("data.json")

#set document(title: "Approval Package — QA #" + str(data.qa_result_id))
#set page(paper: "a4", margin: (top: 2cm, bottom: 2cm, left: 2.5cm, right: 2.5cm))
#set text(font: "Helvetica", size: 10pt)
#set par(leading: 0.65em)

// ── Cover Page ──

#align(center)[
  #v(4cm)
  #text(size: 28pt, weight: "bold")[Email Approval Package]
  #v(0.5cm)
  #text(size: 14pt, fill: rgb("#666"))[Quality Assurance Summary]
  #v(1cm)
  #line(length: 60%, stroke: 0.5pt + rgb("#ccc"))
  #v(1cm)
  #text(size: 11pt, fill: rgb("#666"))[Generated: #data.generated_at]
  #v(3cm)

  #let badge-color = if data.passed { rgb("#22c55e") } else { rgb("#f59e0b") }
  #let badge-text = if data.passed { "READY FOR APPROVAL" } else { "REVIEW REQUIRED" }
  #rect(fill: badge-color, radius: 4pt, inset: (x: 16pt, y: 8pt))[
    #text(fill: white, weight: "bold", size: 14pt)[#badge-text]
  ]
]

#pagebreak()

// ── Quality Summary ──

#heading(level: 1)[Quality Summary]

#table(
  columns: (1fr, 1fr),
  stroke: 0.5pt + rgb("#ddd"),
  inset: 8pt,
  [*Quality Score*], [#str(calc.round(data.overall_score * 100, digits: 1))%],
  [*Checks Passed*], [#str(data.checks_passed) of #str(data.checks_total)],
  [*Status*], [#if data.passed { "All checks passed" } else { "Some checks require attention" }],
)

#v(1cm)

// ── Brand Compliance ──

#heading(level: 1)[Brand Compliance]

#let checks = data.at("checks", default: ())
#let brand_check = checks.filter(c => c.name == "brand_compliance")

#if brand_check.len() > 0 [
  #let bc = brand_check.first()
  #if bc.passed [
    #text(fill: rgb("#22c55e"))[✓ Brand guidelines verified — colors, typography, and logo usage comply with brand standards.]
  ] else [
    #text(fill: rgb("#f59e0b"))[⚠ Brand compliance issues detected: #bc.details]
  ]
] else [
  #text(fill: rgb("#666"))[Brand compliance check not included in this run.]
]

#v(1cm)

// ── Key Checks ──

#heading(level: 1)[Quality Checks Overview]

#table(
  columns: (3fr, auto, 4fr),
  stroke: 0.5pt + rgb("#ddd"),
  inset: 8pt,
  table.header([*Check*], [*Status*], [*Notes*]),
  ..for check in checks {
    (
      check.name,
      if check.passed { text(fill: rgb("#22c55e"))[Pass] } else { text(fill: rgb("#ef4444"))[Fail] },
      if check.passed { "—" } else { check.details },
    )
  }
)

#pagebreak()

// ── Approval Section ──

#heading(level: 1)[Approval]

#v(1cm)
#text[By signing below, you confirm that the email template has been reviewed and is approved for production deployment.]

#v(2cm)

#grid(
  columns: (1fr, 1fr),
  gutter: 2cm,
  [
    #line(length: 100%, stroke: 0.5pt)
    #v(0.3cm)
    *Name*
    #v(1.5cm)
    #line(length: 100%, stroke: 0.5pt)
    #v(0.3cm)
    *Date*
  ],
  [
    #line(length: 100%, stroke: 0.5pt)
    #v(0.3cm)
    *Signature*
    #v(1.5cm)
    #line(length: 100%, stroke: 0.5pt)
    #v(0.3cm)
    *Title / Role*
  ],
)

// ── Footer ──
#v(1fr)
#line(length: 100%, stroke: 0.5pt + rgb("#ddd"))
#text(size: 8pt, fill: rgb("#999"))[
  Generated by Merkle Email Innovation Hub • #data.generated_at
]
