// QA Report — Merkle Email Innovation Hub
// Reads data from data.json (written by TypstRenderer)

#let data = json("data.json")

#set document(title: "QA Report #" + str(data.qa_result_id))
#set page(paper: "a4", margin: (top: 2cm, bottom: 2cm, left: 2.5cm, right: 2.5cm))
#set text(font: "Helvetica", size: 10pt)
#set par(leading: 0.65em)

// ── Cover Page ──

#align(center)[
  #v(4cm)
  #text(size: 28pt, weight: "bold")[QA Report]
  #v(0.5cm)
  #text(size: 14pt, fill: rgb("#666"))[Merkle Email Innovation Hub]
  #v(1cm)
  #line(length: 60%, stroke: 0.5pt + rgb("#ccc"))
  #v(1cm)
  #text(size: 12pt)[Result ID: *#str(data.qa_result_id)*]
  #v(0.3cm)
  #text(size: 11pt, fill: rgb("#666"))[Generated: #data.generated_at]
  #v(2cm)

  #let badge-color = if data.passed { rgb("#22c55e") } else { rgb("#ef4444") }
  #let badge-text = if data.passed { "PASSED" } else { "FAILED" }
  #rect(fill: badge-color, radius: 4pt, inset: (x: 16pt, y: 8pt))[
    #text(fill: white, weight: "bold", size: 16pt)[#badge-text]
  ]
  #v(0.5cm)
  #text(size: 14pt)[Score: *#str(calc.round(data.overall_score * 100, digits: 1))%*]
]

#pagebreak()

// ── Executive Summary ──

#heading(level: 1)[Executive Summary]

#table(
  columns: (1fr, 1fr),
  stroke: 0.5pt + rgb("#ddd"),
  inset: 8pt,
  [*Overall Score*], [#str(calc.round(data.overall_score * 100, digits: 1))%],
  [*Status*], [#if data.passed { "Passed" } else { "Failed" }],
  [*Checks Passed*], [#str(data.checks_passed) / #str(data.checks_total)],
  [*Resilience Score*], [#if data.at("resilience_score", default: none) != none { str(calc.round(float(str(data.resilience_score)) * 100, digits: 1)) + "%" } else { "N/A" }],
  [*Created*], [#data.at("created_at", default: "—")],
)

#v(0.5cm)

// Top issues
#let top_issues = data.at("top_issues", default: ())
#if top_issues.len() > 0 [
  #heading(level: 2)[Top Issues]

  #table(
    columns: (2fr, 1fr, 3fr),
    stroke: 0.5pt + rgb("#ddd"),
    inset: 8pt,
    table.header([*Check*], [*Severity*], [*Details*]),
    ..for issue in top_issues {
      (issue.name, issue.severity, issue.details)
    }
  )
]

#pagebreak()

// ── Check Results ──

#heading(level: 1)[Check Results]

#let checks = data.at("checks", default: ())

#table(
  columns: (2fr, auto, auto, 1fr, 3fr),
  stroke: 0.5pt + rgb("#ddd"),
  inset: 6pt,
  table.header([*Check*], [*Status*], [*Score*], [*Severity*], [*Details*]),
  ..for check in checks {
    (
      check.name,
      if check.passed { text(fill: rgb("#22c55e"))[✓] } else { text(fill: rgb("#ef4444"))[✗] },
      str(calc.round(check.score * 100, digits: 0)) + "%",
      check.severity,
      check.details,
    )
  }
)

// ── Screenshots (conditional) ──

#let screenshots = data.at("screenshots", default: ())
#if screenshots.len() > 0 [
  #pagebreak()
  #heading(level: 1)[Rendering Screenshots]

  #for shot in screenshots [
    #heading(level: 2)[#shot.at("label", default: "Preview")]
    // Screenshots would be embedded as base64 images
    #v(0.5cm)
  ]
]

// ── Chaos Tests (conditional) ──

#if data.at("include_chaos", default: false) and data.at("resilience_score", default: none) != none [
  #pagebreak()
  #heading(level: 1)[Chaos / Resilience Testing]

  #text[Resilience Score: *#str(calc.round(float(str(data.resilience_score)) * 100, digits: 1))%*]
  #v(0.5cm)
  #text(fill: rgb("#666"))[Chaos testing evaluates template robustness under simulated email client mutations.]
]

// ── Recommendations ──

#let failed = data.at("checks", default: ()).filter(c => not c.passed)
#if failed.len() > 0 [
  #pagebreak()
  #heading(level: 1)[Recommendations]

  #for check in failed [
    - *#check.name* (#check.severity): #check.details
  ]
]

// ── Footer ──
#v(1fr)
#line(length: 100%, stroke: 0.5pt + rgb("#ddd"))
#text(size: 8pt, fill: rgb("#999"))[
  Generated by Merkle Email Innovation Hub • #data.generated_at
]
