// Visual Regression Report
// Reads data from data.json (written by TypstRenderer)

#let data = json("data.json")

#set document(title: "Regression Report — " + data.entity_type + " #" + str(data.entity_id))
#set page(paper: "a4", margin: (top: 2cm, bottom: 2cm, left: 2.5cm, right: 2.5cm))
#set text(font: "Helvetica", size: 10pt)
#set par(leading: 0.65em)

// ── Cover Page ──

#align(center)[
  #v(4cm)
  #text(size: 28pt, weight: "bold")[Visual Regression Report]
  #v(0.5cm)
  #text(size: 14pt, fill: rgb("#666"))[Rendering Comparison Analysis]
  #v(1cm)
  #line(length: 60%, stroke: 0.5pt + rgb("#ccc"))
  #v(1cm)
  #text(size: 12pt)[Entity: *#data.entity_type* \##str(data.entity_id)]
  #v(0.3cm)
  #text(size: 11pt, fill: rgb("#666"))[Generated: #data.generated_at]
]

#pagebreak()

// ── Baselines Overview ──

#heading(level: 1)[Rendering Baselines]

#let baselines = data.at("baselines", default: ())

#if baselines.len() > 0 [
  #text[Found *#str(baselines.len())* baseline(s) for this entity.]
  #v(0.5cm)

  #table(
    columns: (auto, 2fr, 2fr, auto),
    stroke: 0.5pt + rgb("#ddd"),
    inset: 6pt,
    table.header([*\#*], [*Client*], [*Created*], [*Status*]),
    ..for (idx, baseline) in baselines.enumerate() {
      (
        str(idx + 1),
        str(baseline.at("client_name", default: "—")),
        str(baseline.at("created_at", default: "—")),
        str(baseline.at("status", default: "—")),
      )
    }
  )
] else [
  #text(fill: rgb("#999"))[No baselines recorded for this entity.]
]

// ── Comparison (conditional) ──

#let comparison = data.at("comparison", default: none)
#if comparison != none [
  #pagebreak()
  #heading(level: 1)[Visual Comparison]

  #let diffs = comparison.at("diffs", default: ())
  #if diffs.len() > 0 [
    #table(
      columns: (2fr, auto, 3fr),
      stroke: 0.5pt + rgb("#ddd"),
      inset: 6pt,
      table.header([*Client*], [*Diff %*], [*Notes*]),
      ..for diff in diffs {
        (
          str(diff.at("client_name", default: "—")),
          str(diff.at("diff_percentage", default: 0)) + "%",
          str(diff.at("notes", default: "—")),
        )
      }
    )
  ] else [
    #text(fill: rgb("#22c55e"))[✓ No visual differences detected between baseline and current rendering.]
  ]
]

// ── Footer ──
#v(1fr)
#line(length: 100%, stroke: 0.5pt + rgb("#ddd"))
#text(size: 8pt, fill: rgb("#999"))[
  Generated by Merkle Email Innovation Hub • #data.generated_at
]
