"""Generate .env.example from Settings model + a docker-compose prelude.

The prelude covers vars consumed by docker-compose (POSTGRES_USER etc.) and
the frontend NextAuth secret — these are not part of `app.core.config.Settings`
but `scripts/check-env-example.sh` requires them to stay documented.

The auto-generated section mirrors `Settings.model_fields` recursively so the
file matches the actual Settings surface (closes 82% drift, F033).

Usage:
    uv run python scripts/generate-env-example.py > .env.example
    make .env.example
"""

from __future__ import annotations

import json
import sys
from collections.abc import Iterator
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pydantic import BaseModel
from pydantic.fields import FieldInfo
from pydantic_core import PydanticUndefined

from app.core.config import Settings

PRELUDE = """\
# ── Docker Stack Environment Variables ──
# This file is generated by scripts/generate-env-example.py — edit there.

# Core
ENVIRONMENT=development
LOG_LEVEL=INFO

# PostgreSQL (docker-compose; backend reads DATABASE__URL)
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=email_hub

# Redis (docker-compose only; backend reads REDIS__URL)
REDIS_PASSWORD=devpassword

# Auth (frontend NextAuth) — generate with: openssl rand -base64 32
AUTH_SECRET=

# ── Backend Settings (auto-generated from app.core.config.Settings) ──
"""


def _is_basemodel(annotation: Any) -> bool:  # noqa: ANN401
    """Return True if the annotation is a Pydantic BaseModel subclass."""
    return isinstance(annotation, type) and issubclass(annotation, BaseModel)


def _format_value(value: Any) -> str:  # noqa: ANN401
    """Render a default value as an env-file string."""
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (list, dict)):
        return json.dumps(value)
    return str(value)


def _resolve_default(info: FieldInfo) -> Any:  # noqa: ANN401
    """Resolve default factory / undefined into a concrete value or sentinel."""
    if info.default is not PydanticUndefined:
        return info.default
    if info.default_factory is not None:
        try:
            return info.default_factory()  # type: ignore[call-arg]
        except TypeError:
            return "<required>"
    return "<required>"


def _emit_field(name: str, info: FieldInfo, prefix: str = "") -> Iterator[str]:
    """Yield env-file lines for a single field, recursing into nested configs."""
    env_name = f"{prefix}{name.upper()}"
    annotation = info.annotation
    if _is_basemodel(annotation):
        yield ""
        yield f"# ── {annotation.__name__} ──"  # type: ignore[union-attr]
        for sub_name, sub_info in annotation.model_fields.items():  # type: ignore[union-attr]
            yield from _emit_field(sub_name, sub_info, prefix=f"{env_name}__")
        return

    default = _resolve_default(info)
    if info.description:
        yield f"# {info.description}"
    yield f"{env_name}={_format_value(default)}"


def main() -> None:
    """Print the full .env.example contents to stdout."""
    print(PRELUDE)
    for name, info in Settings.model_fields.items():
        for line in _emit_field(name, info):
            print(line)


if __name__ == "__main__":
    main()
